#!/bin/sh

set -e

if [ ! -d "shunit2-2.1.8" ]
then
    wget -qO- https://github.com/kward/shunit2/archive/refs/tags/v2.1.8.tar.gz | tar -xz
fi


DOCKER_BUILD_PREFIX="docker build"
DOCKER_RUN_PREFIX="docker run --rm -v ./:/sandbox/input -v ./output:/sandbox/output -v ./output:/sandbox/scalogs"

set +e
