#!/bin/sh

set -e

if [ ! -d "shunit2-2.1.8" ]
then
    wget -qO- https://github.com/kward/shunit2/archive/refs/tags/v2.1.8.tar.gz | tar -xz
fi

INPUT_DIR=$(pwd)/input
OUTPUT_DIR=$(pwd)/output

DOCKER_BUILD_PREFIX="docker build -t delete:me --progress plain $BUILD_COMPAT"
DOCKER_RUN_PREFIX="docker run --rm -v $INPUT_DIR:/sandbox/input -v $OUTPUT_DIR:/sandbox/output -v $OUTPUT_DIR:/sandbox/scalogs"
DOCKER_DELETE="docker image rm -f delete:me && docker system prune -f"

set +e
