LogsDirectory: /scalogs
ResolverResultPath: /output/sca-results.json

# You can place custom configuration parameters below this comment block.  Modifying the 
# configuration parameters above this line may cause SCAResolver to malfunction when running
# in the context of this container.

