name: build-ci
on: 
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  
  image-build-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v3
      - name: Execute Sandbox Build Tests
        run: |
        cd ${{ github.workspace }}/sandbox/tests
        ./build-tests.sh

  execution-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v3
      - name: Execute Sandbox Execution Tests
        run: |
        cd ${{ github.workspace }}/sandbox/tests
        ./execute-tests.sh
    
