name: build-ci
on: 
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  
  image-build-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Execute Sandbox Build Tests
        run: |
          cd ${{ github.workspace }}/sandbox/tests
          ./build-tests.sh

  execution-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Execute Sandbox Execution Tests
        run: |
          cd ${{ github.workspace }}/sandbox/tests
          ./execute-tests.sh
    
