name: build-ci
on:
  workflow_dispatch:
  push:

jobs:
  
  image-build-unit-tests-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: linux/amd64
      - name: Execute Sandbox Build Tests
        run: |
          cd ${{ github.workspace }}/sandbox/tests
          ./build-tests-linux-amd64.sh

  execution-unit-tests-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: linux/amd64
          append: --use --driver=docker-container
      - name: Execute Sandbox Execution Tests
        run: |
          cd ${{ github.workspace }}/sandbox/tests
          ./execute-tests-linux-amd64.sh
    
