on:
  workflow_dispatch:
  push:

env:
  BUILD_COMPAT: ${{ vars.WORKFLOW_BUILD_COMPAT }}

jobs:
  image-build-unit-tests:
    strategy:
      max-parallel: 3
      matrix:
        base_img:
          - "cimg/openjdk:17.0"
          - "amazoncorretto:11-alpine3.14"
          - "gradle:8-jdk11-alpine"
          - "gradle:8-jdk17-alpine"
          # - "gradle:8-jdk17-graal"
          - "amazonlinux:latest"
          - "redhat/ubi9:latest"
          - "redhat/ubi9-minimal:latest"
          - "redhat/ubi8:latest"
          - "redhat/ubi8-minimal:latest"
          - "buildpack-deps:latest"
          - "buildpack-deps:sid"
          - "eclipse-temurin:latest"
          - "amazoncorretto:8"
          - "amazoncorretto:11"
          - "amazoncorretto:8-alpine3.14"
          - "amazoncorretto:11-alpine3.14"
          - "debian:latest"
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        with:
          install: true
          platforms: linux/amd64
      - name: Execute Extended Image Build Tests
        shell: bash
        run: |
          cd ${{ github.workspace }}/build-environment/tests
          BASE_IMG=${{ matrix.base_img }} ./autobuild-tests.sh

       
  image-negative-build-unit-tests-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        with:
          install: true
          platforms: linux/amd64
      - name: Execute Sandbox Build Negative Tests
        run: |
          cd ${{ github.workspace }}/build-environment/tests
          ./build-negative-tests-linux-amd64.sh

  execution-unit-tests-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        with:
          install: true
          use: true
          platforms: linux/amd64
      - name: Execute Sandbox Execution Tests
        env:
          TEST_TENANT: ${{ secrets.SCA_TENANT }}
          TEST_USER: ${{ secrets.SCA_USER }}
          TEST_PASSWORD: ${{ secrets.SCA_PASSWORD }}
          TEST_APIKEY: ${{ secrets.CXONE_APIKEY }}
        run: |
          cd ${{ github.workspace }}/build-environment/tests
          ./execute-tests-linux-amd64.sh
    
  dispatcher-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install packages
        run: pip install -r ${{ github.workspace }}/legacy/enhanced-cxflow-scaresolver/dispatcher/requirements.txt
      - name: Execute Unit Tests
        run: python -m unittest discover -v -p test_*.py -s ${{ github.workspace }}/legacy/enhanced-cxflow-scaresolver/dispatcher

  docs-manual-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Build PDF Manual
        uses: xu-cheng/latex-action@f1ca82cbed861b3534e2997dd584944f55b884ed
        with:
          root_file: docs/_main.tex
          work_in_root_file_dir: true

  docs-release-notes-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Build PDF Release Notes
        uses: xu-cheng/latex-action@f1ca82cbed861b3534e2997dd584944f55b884ed
        with:
          root_file: release_notes/release_notes.tex
          work_in_root_file_dir: true
