on: 
    workflow_call:
      inputs:
        tag:
          description: 'The version tag string'
          required: true
          type: string
        prerelease:
          description: 'Set to true if publishing a pre-release.'
          required: true
          type: boolean
      secrets:
          PACKAGE_USER:
              required: true
          PACKAGE_PAT:
              required: true
              
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag repo ${{ inputs.tag }}
        uses: richardsimko/update-tag@e173a8ef8f54ab526a91dad6139a25efed62424c
        with:
          tag_name: ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  publish-release:
    needs: [create-tag]
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ inputs.tag }}
      prerelease: ${{ inputs.prerelease }}
    secrets:
      PACKAGE_USER: ${{ secrets.PACKAGE_USER }}
      PACKAGE_PAT: ${{ secrets.PACKAGE_PAT }}

  remove-tag-on-failure:
    needs: [create-tag, publish-release]
    runs-on: ubuntu-latest
    if: always()
    env:
      BUILD_SUCCESS: ${{ needs.publish-release.outputs.success }}
    steps:
      # - uses: technote-space/workflow-conclusion-action@95f9a08c3e6565ffb9134e90fd181697681cb55b
      - name: Fetch Code
        uses: actions/checkout@v3
        if: env.BUILD_SUCCESS != 'true'

      - name: Remove CodeTag
        run: git push origin ':refs/tags/${{ inputs.tag }}'
        if: env.BUILD_SUCCESS != 'true'
    
        
    
  
  
    