name: Republish a Release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x, must already exist, must be the latest release tag.'
        required: true
        type: string
      tag-packages-as-latest:
        description: 'Tag any re-published container images with "latest"'
        required: true
        type: boolean
        default: false
    

jobs:
    make-tag-string:
        runs-on: ubuntu-latest
        outputs:
          tag: ${{ steps.tag-string.outputs.tag }}
        steps:
          - name: Create tag
            run: |
              echo "tag=v${{ inputs.version }}" >> $GITHUB_OUTPUT
            id: tag-string
          
    validate-tag-exists:
        runs-on: ubuntu-latest
        needs: [make-tag-string]
        steps:
          - name: Fetch Code
            continue-on-error: true
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
            with:
              ref: refs/tags/${{ needs.make-tag-string.outputs.tag }}
          - name: Fail if tag ${{ needs.make-tag-string.outputs.tag }} missing
            run: git describe --tags

    republish-release:
        needs: [make-tag-string, validate-tag-exists]
        uses: ./.github/workflows/build.yml
        with:
            tag: ${{ needs.make-tag-string.outputs.tag }}
            prerelease: false
            tag-packages-as-latest: ${{ inputs.tag-packages-as-latest }}
        secrets:
            PACKAGE_USER: ${{ secrets.PACKAGE_USER }}
            PACKAGE_PAT: ${{ secrets.PACKAGE_PAT }}
    